name: Generate carousel.json

on:
  push:
    branches: [main]

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build JSON
        run: |
          IMAGES_DIR="assets/images/carousel"
          OUTPUT_FILE="carousel.json"

          echo "[" > $OUTPUT_FILE
          find "$IMAGES_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" -o -iname "*.svg" \) \
            | sed 's/^/  "/; s/$/"/' | paste -sd "," - >> $OUTPUT_FILE
          echo "]" >> $OUTPUT_FILE

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add carousel.json
          git commit -m "Update carousel.json" || echo "No changes"
          git push
